/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_env_sensing                    25
#define gattdb_temperature                    27
#define gattdb_automation_io                  29
#define gattdb_digital                        31
#define gattdb_characteristic_presentation_format 32
#define gattdb_characteristic_user_description 33
#define gattdb_characteristic_extended_properties 34
#define gattdb_value_trigger_setting          35
#define gattdb_time_trigger_setting           36
#define gattdb_number_of_digitals             37
#define gattdb_ota                            38
#define gattdb_ota_control                    40


#endif // __GATT_DB_H
